### ISSUE TITLE
Update Openai wrapper to add speech to text functionality

### ISSUE THREAD

**Issue by Barqawiz** [Barqawiz/IntelliNode#17]
Update the openai wrapper to add the audio function (speech 2 text) from openai api.

Openai audio reference: 
https://platform.openai.com/docs/api-reference/audio

--------------

1. Update the IntelliNode [Openai wrapper](https://github.com/Barqawiz/IntelliNode/blob/main/IntelliNode/wrappers/OpenAIWrapper.js) with audio function:

Function name:
```
async speechToText(params) { 
//TODO: add the implementation details.
}
```

2. You can add the audio related helpers like loading audio files in `AudioHelper`.

--------------

<br/>

3. Add unit test case in `OpenAIWrapper.test.js` and ensure it works as expected.

- Create below function with testing details:

```
async function testSpeechToText() { }
```

--------------

<br/>

**Comment by Barqawiz** [comment]
Yes you are right, the description confused the task. 

I just fixed the description.

**Comment by pushoo-sharma** [comment]
Thanks, 
1. Do we have any sample account to test OpenAI APIs on running test cases
2. I have created a new directory for storing audio files under `samples/audios`, do I need to pull it from somewhere or will that be fine?

@Barqawiz

**Comment by Barqawiz** [comment]
- any small testing file is fine.
- will send you the openai key in private.
