### ISSUE TITLE
Is it possible to combine allow to custom base openai API to work through brokers who provide the service?

### ISSUE THREAD

**Issue by yf007** [Barqawiz/IntelliNode#21]
If it is possible to add both on the site itself (which is excellent in its own right) and in the code here at GitHub

Thanks

**Comment by Barqawiz** [comment]
The openai proxy service is deployed to the node module and soon will be available in the show case app.

**Comment by Barqawiz** [comment]
The proxy settings publish to https://show.intellinode.ai/ settings.
